pzk/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get( '/', array( 'as' => 'glowna', function() {
	return View::make( 'glowna' );
} ) );

Route::resource( 'aktualnosc', 'AktuController',
  array( 'except' => array( 'index' ) ) );

Route::resource( 'kopalnia', 'KopalniaController' );
Route::get( 'kopalnia/search', array( 'as' => 'kopalnia.search', 'uses' => 'KopalniaController@search' ) );

Route::get( 'json/obrazki/{path}', 'ResourceController@getObrazki' );

Route::get('o_stronie', function()
{
  return View::make('o_stronie');
});

Route::get('contact', 'PagesController@contact');

Route::resource('users', 'UsersController');

pzk/app/models/Kopalnia.php
<?php

class Kopalnia extends Eloquent
{
  protected $table = 'kopalnia';

  protected $primaryKey = 'id';

  protected $guarded = array( 'id' );

  public static $rules = array(
    'Rodzic' => 'max:200',
    'Isbn' => 'max:15',
    'Tytul' => 'required|max:175',
    'CzyBrakujeInfo' => 'integer|min:0|max:1',
    'PubMiesiac' => 'integer|min:1|max:12',
    'PubRok' => 'integer|min:1800|max:2050',
    'MiejsceWydania' => 'max:40',
    'Rodzaj' => 'required|in:pismo,kolekcja,numer,portal,dzial,ksiazka,praca,artykul,rozdzial,wywiad,audiowideo,audycja,notka,inny',
    'Objetosc' => 'max:30',
    'Jezyk' => 'max:2',
  );

  private $rodzaje = array(
    "pismo" => "czasopismo",
    "numer" => "numer",
    "portal" => "portal",
    "dzial" => "dział",
    "artykul" => "artykuł",
    "wywiad" => "wywiad",
    "notka" => "notka prasowa",
    "kolekcja" => "kolekcja",
    "ksiazka" => "książka",
    "rozdzial" => "rozdział",
    "praca" => "praca naukowa",
    "audycja" => "audycja",
    "audiowideo" => "nagranie audio lub wideo",
    "inny" => "inny" );

  private $jezyki = array(
    "pl" => "polski", "en" => "angielski", "fr" => "francuski", "ru" => "rosyjski",
    "de" => "niemiecki", "ua" => "ukraiński", "cz" => "czeski", "sk" => "słowacki",
    "lt" => "litewski", "se" => "szwedzki", "es" => "hiszpański", "it" => "włoski",
    "??" => "inny" );

  public function PrintRodzaj()
  {
    return $this->rodzaje[ $this->Rodzaj ];
  }

  public function PrintJezyk()
  {
    return $this->jezyki[ $this->Jezyk ];
  }

  public function zawartosc()
  {
    return $this->hasMany( 'Kopalnia', 'RodzicId' );
  }

  public function rodzic()
  {
    return $this->belongsTo( 'Kopalnia', 'RodzicId' );
  }

  public function zawartoscDzialu()
  {
    return $this->hasMany( 'Kopalnia', 'DzialId' );
  }

  public function dzial()
  {
    return $this->belongsTo( 'Kopalnia', 'DzialId' );
  }

  public function autorzy()
  {
    // To get to the Typ field, call $author->pivot->Typ
    return $this->belongsToMany( 'Autor', 'kopalnia_autorzy', 'KopalniaId', 'AutorId' )->withPivot( array( 'Typ' ) );
  }

  public function tylkoAutorzy( $typ )
  {
    return $this->autorzy->filter( function ( $a ) use ( $typ )
    {
      return $a->Typ() == $typ;
    } );
  }

  public function autorzyView()
  {
    $items = $this->autorzy->map( function ( $a )
    {
      $item = "<a href=\"#\">{$a->Imiona} {$a->Nazwisko}</a>";
      if( 'autor' == $a->Typ() )
      {
        $item = "<b>$item</b>";
      } else if( 'redaktor' == $a->Typ() )
      {
        $item .= " (redakcja)";
      } else if( 'tlumacz' == $a->Typ() )
      {
        $item .= " (tłumaczenie)";
      } else if( 'wywiadowca' == $a->Typ() )
      {
        $item .= " (zadawał/a pytania)";
      }

      return $item;
    } );

    return implode( ", ", $items->all() );
  }

  public function wydawcy()
  {
    return $this->belongsToMany( 'Wydawca', 'kopalnia_wydawcy', 'KopalniaId', 'WydawcaId' );
  }

  public function wydawcyView()
  {
    $items = $this->wydawcy->map( function ( $w )
    {
      $item = $w->Nazwa;
      if( $w->Url != null )
      {
        $item = "<a href=\"{$w->Url}\">$item</a>";
      }
      $item = "<b>$item</b>";
      return $item;
    } );

    return implode( ", ", $items->all() );
  }

  public function haslaPrzedmiotowe()
  {
    return $this->belongsToMany( 'HasloPrzedm', 'kopalnia_hasla_przedm', 'KopalniaId', 'HasloId' );
  }

  public function haslaPrzedmiotoweView()
  {
    $items = $this->haslaPrzedmiotowe->map( function ( $h )
    {
      $item = "<a href=\"#\">$h->Haslo</a>";
      return $item;
    } );

    return implode( "<br> ", $items->all() );
  }
}

pzk/app/controllers/KopalniaController.php
<?php

class KopalniaController extends \BaseController
{

  /**
   * Display the index page.
   *
   * @return Response
   */
  public function index()
  {
    return View::make( 'kopalnia.index' );
  }

  /**
   * Display the specified resource.
   *
   * @param  int $id
   *
   * @return Response
   */
  public function show( $id )
  {
    $kopalnia = Kopalnia::find( $id );
    if( is_null( $kopalnia ) )
    {
      return Redirect::route( 'kopalnia.index' )
        ->with( 'problem', 'Fiszka z identyfikatorem ' . $id . ' nie istnieje.' );
    } else
    {
      return View::make( 'kopalnia.view', compact( 'kopalnia' ) );
    }
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return Response
   */
  public function create()
  {
    return View::make( 'kopalnia.index' );
  }

  /**
   * Store a newly created resource in storage.
   *
   * @return Response
   */
  public function store()
  {
    return Redirect::route( 'kopalnia.index' );
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int $id
   *
   * @return Response
   */
  public function edit( $id )
  {
    return Redirect::route( 'kopalnia.index' );
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  int $id
   *
   * @return Response
   */
  public function update( $id )
  {
    return Redirect::route( 'kopalnia.index' );
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int $id
   *
   * @return Response
   */
  public function destroy( $id )
  {
    return Redirect::route( 'kopalnia.index' );
  }

  /**
   * Remove the specified resource from storage.
   *
   * @return Response
   */
  public function search()
  {
    return "Search page!";
  }

}

pzk/app/views/kopalnia/index.blade.php
@extends('layouts.main')

@section('main')

<p class="francrozdzial"><span class="blackcourier">Kopalnia Wiedzy o Komiksie</span></p>

<div align="center">
  <table border="0" width="100%">
    <tbody>
      <tr>
        <td class="blackcourier">

          <p>
            <strong>Kopalnia Wiedzy o Komiksie</strong> (w skrócie KWoK)
            to bibliograficzny katalog (baza danych), zawierający informacje
            o wszelkiego rodzaju publikacjach, dotyczących komiksu: artykułach,
            recenzjach, pracach naukowych, książkach, czasopismach itd., zarówno
            polskojęzycznych, jak i zagranicznych. Zarejestrowani użytkownicy
            mogą <strong>dopisywać komentarze i linki</strong>.
          <p/>

          <p>
            W chwili obecnej Kopalnia zawiera N publikacji.
          </p>

          <p>
            Dodatkowe linki:
            <ul>
              <li>
                {{ link_to_route( 'kopalnia.search', "Wyszukiwanie zaawansowane", null, array( 'class' => 'link1' ) ) }}
              </li>
              <li>
                {{ link_to_route( 'kopalnia.create', "Dodaj nowy wpis do Kopalni", null, array( 'class' => 'link1' ) ) }}
              </li>
            </ul>
          </p>

        </td>
      </tr>
    </tbody>
  </table>
</div>

@stop

pzk/app/views/kopalnia/view.blade.php
@extends('layouts.main')

@section('main')

    <div class="kopalnia-top-div">
      <div class="col-md-12 kopalnia-content-div">
        <p>
          <a href="#"><span class="recka-title kopalnia-title">{{$kopalnia->Tytul}}</span></a>
          <span class="inobtrusive">({{$kopalnia->PrintRodzaj()}})</span>
        </p>
@if( $kopalnia->RodzicId != null  )
        <p class="blockquote">
          <span class="inobtrusive">w:</span>
          <a href="#">{{$kopalnia->rodzic->Tytul}}</a>
  @if( $kopalnia->DzialId != null )
          <span class="inobtrusive">({{$kopalnia->rodzic->PrintRodzaj()}};
          dział: </span><a href="#">{{$kopalnia->dzial->Tytul}}</a><span class="inobtrusive">)</span>
  @else
          <span class="inobtrusive">({{$kopalnia->rodzic->PrintRodzaj()}})</span>
  @endif
        </p>
@elseif( $kopalnia->Rodzic != null  )
        <p class="blockquote">
          <span class="inobtrusive">w:</span>
          <a href="#">{{$kopalnia->Rodzic}}</a>
        </p>
@endif

@if( $kopalnia->autorzy->count() > 0 )
        <p>
        {{$kopalnia->autorzyView()}}
        </p>
@endif

@if( $kopalnia->wydawcy->count() > 0 || $kopalnia->MiejsceWydania != null )
        <p>
  @if( $kopalnia->wydawcy->count() > 0 )
    {{$kopalnia->wydawcyView().($kopalnia->MiejsceWydania != null ? ", " : "")}}
  @endif
  @if( $kopalnia->MiejsceWydania != null )
    {{$kopalnia->MiejsceWydania.($kopalnia->PubRok != null ? ": ".$kopalnia->PubRok : "")}}
  @endif
        </p>
@endif

@if( $kopalnia->PubMiesiac != null && $kopalnia->PubRok != null )
        <p>
          <span class="inobtrusive">Data publikacji:</span> {{Converter::Miesiac($kopalnia->PubMiesiac)}} {{$kopalnia->PubRok}}
        </p>
@endif

@if( $kopalnia->Isbn != null )
        <p>
          <span class="inobtrusive">ISBN:</span> {{$kopalnia->Isbn}}
        </p>
@endif

@if( $kopalnia->Objetosc != null )
        <p>
          <span class="inobtrusive">Objętość:</span> {{$kopalnia->Objetosc}}
        </p>
@endif

@if( $kopalnia->Jezyk != null )
        <p>
          <span class="inobtrusive">Język:</span> {{$kopalnia->PrintJezyk()}}
        </p>
@endif
      </div>
    </div>
    <div class="row kopalnia-top-div no-margin">
      <div class="col-md-8 kopalnia-content-div">

@if( $kopalnia->haslaPrzedmiotowe->count() > 0 )
        <p class="inobtrusive">
          Hasła przedmiotowe:
        </p>
        <p class="blockquote">
          {{$kopalnia->haslaPrzedmiotoweView()}}
        </p>
@endif

@if( $kopalnia->Opis != null && $kopalnia->Opis != "" )
        <p class="inobtrusive">
          Opis:
        </p>
        <p class="blockquote">
          {{$kopalnia->Opis}}
        </p>
@endif

      </div>

      <div class="col-md-4 kopalnia-content-div left-dashed-border">

@if( $kopalnia->SlowaKluczowe != null && $kopalnia->SlowaKluczowe != "" )
        <p class="inobtrusive">
          Słowa kluczowe:
        </p>
        <p class="blockquote">
          {{$kopalnia->SlowaKluczowe}}
        </p>
@endif

        <p class="inobtrusive">
          Linki:
        </p>
        <p class="blockquote">
          <a href="#">Recenzja w <em>Gazecie Wyborczej</em></a><br>
          <a href="#">Tekst, którego dotyczy ten artykuł</a>
        </p>
      </div>
    </div>

@stop